services:
  db:
    restart: always
    image: postgis/postgis:16-3.4
    env_file: envs/local.env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    hostname: db

  rabbitmq:
    image: rabbitmq:3.9.16-management
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - "5672"

  api:
    build:
      context: ./api
    depends_on:
      - db
      - rabbitmq
    ports:
      - "8000:8000"
    command: ["bash", "/api/start_server.sh", "db"]


volumes:
  db-data:
