services:
  db:
    restart: always
    image: postgis/postgis:16-3.4
    env_file: envs/local.env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    hostname: db

  rabbitmq:
    image: rabbitmq:3.9.16-management
    env_file: envs/local.env
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - "5672"
    hostname: rabbit

  api:
    build:
      context: ./api
    depends_on:
      - db
      - rabbitmq
    ports:
      - "8000:8000"

  celery_api:
    build:
      context: ./api
    depends_on:
      - api
    command: ["bash", "run_celery.sh"]


  core:
    build:
      context: ./core
    depends_on:
      - db
      - rabbitmq

  worker:
    build:
      context: ./worker
    depends_on:
      - db
      - rabbitmq


volumes:
  db-data:
